version: '3'

services:
  postgres:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simi
      - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    depends_on:
      - postgres
    image: sogis/simi
    environment:
    - CUBA_DATASOURCE_USERNAME=postgres
    - CUBA_DATASOURCE_PASSWORD=postgres
    - CUBA_DATASOURCE_DBNAME=simi
    - CUBA_DATASOURCE_HOST=postgres
    - CUBA_DATASOURCE_PORT=5432
    - CUBA_AUTOMATICDATABASEUPDATE=true
    ports:
      - "8080:8080"