version: "3"
services:
  schemareader:
    image: sogis/simi_schemareader
    environment:
      - SPRING_APPLICATION_JSON={"dbs":[{"key":"simi","url":"jdbc:postgresql://devdb:5432/simi","user":"postgres","pass":"postgres"}]}
    ports:
      - "8081:8080"
  devdb:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - "./.pgdata:/var/lib/postgresql/data/pgdata"